// generated by pipeline/extract_selects.py — chosen Seedance take per shot + measured lip-sync lag
export const SELECT = {
 "sd01": {
  "start": 0.0,
  "lag": 0.0
 },
 "sd02": {
  "start": 5.2,
  "lag": -0.041667
 },
 "sd03": {
  "start": 10.4,
  "lag": -0.25
 },
 "sd04": {
  "start": 12.7,
  "lag": 0.0
 },
 "sd05": {
  "start": 21.5,
  "lag": -0.291667
 },
 "sd06": {
  "start": 25.0,
  "lag": 0.333333
 },
 "sd07": {
  "start": 30.0,
  "lag": 0.0
 },
 "sd08": {
  "start": 35.5,
  "lag": 0.0
 },
 "sd09": {
  "start": 61.4,
  "lag": -0.083333
 },
 "sd10": {
  "start": 71.0,
  "lag": 0.0
 },
 "sd11": {
  "start": 75.0,
  "lag": 0.125
 },
 "sd12": {
  "start": 81.0,
  "lag": -0.208333
 },
 "sd13": {
  "start": 93.3,
  "lag": -0.333333
 },
 "sd14": {
  "start": 97.2,
  "lag": -0.083333
 },
 "sd15": {
  "start": 102.8,
  "lag": -0.083333
 },
 "sd16": {
  "start": 107.5,
  "lag": 0.0
 },
 "sd17": {
  "start": 112.0,
  "lag": 0.0
 },
 "sd18": {
  "start": 118.0,
  "lag": 0.0
 },
 "se01": {
  "start": 0.0,
  "lag": 0
 },
 "se02": {
  "start": 55.45,
  "lag": 0
 },
 "se03": {
  "start": 67.17,
  "lag": 0
 },
 "se04": {
  "start": 47.55,
  "lag": 0
 },
 "se05": {
  "start": 49.36,
  "lag": 0
 },
 "se06": {
  "start": 74.76,
  "lag": 0
 },
 "se07": {
  "start": 78.11,
  "lag": 0
 },
 "se08": {
  "start": 89.87,
  "lag": 0
 },
 "se10": {
  "start": 107.79,
  "lag": 0
 },
 "se09": {
  "start": 115.265,
  "lag": 0
 },
 "se08b": {
  "start": 79.0,
  "lag": 0
 }
};
