"""Extract rotoscope guides for every selected take and write render/src/selects.js."""
import json, os, sys
from concurrent.futures import ProcessPoolExecutor
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from roto_extract import process

HERE = os.path.dirname(os.path.abspath(__file__))
SEL = json.load(open(os.path.join(HERE, "selects.json")))
PROD = "/tmp/work/sd/prod"                       # all Seedance takes (working dir)
ARCHIVE = os.path.join(HERE, "base_clips")       # the selected takes, archived in the repo (CRF 25 re-encode)
GUIDES = "/tmp/work/guides"


def job(item):
    sid, s = item
    out = f"{GUIDES}/{sid}"
    stamp = f"{out}/.src"
    if os.path.exists(stamp) and open(stamp).read() == s["file"] and "--force" not in sys.argv:
        return sid, "cached"
    src = f"{PROD}/{s['file']}"
    if not os.path.exists(src): src = f"{ARCHIVE}/{s['file']}"
    n, key = process(src, out)
    open(stamp, "w").write(s["file"])
    return sid, f"{n} frames, key={key}"


if __name__ == "__main__":
    only = [a for a in sys.argv[1:] if not a.startswith("--")]
    items = [(k, v) for k, v in SEL.items() if not only or k in only]
    with ProcessPoolExecutor(max_workers=4) as ex:
        for sid, msg in ex.map(job, items):
            print(sid, msg, flush=True)
    js = "// generated by pipeline/extract_selects.py — chosen Seedance take per shot + measured lip-sync lag\n"
    js += "export const SELECT = " + json.dumps({k: {"start": v["start"], "lag": v.get("lag", 0)} for k, v in SEL.items()}, indent=1) + ";\n"
    open(os.path.join(HERE, "..", "render", "src", "selects.js"), "w").write(js)
