import json
T=json.load(open('timing.json'))
def f(t): m=int(t//60); return f"{m:02d}:{t-60*m:06.3f}"
L=[]
L.append("# Rewind - timing notes\n")
L.append("Generated by `build_timing.py` / `write_notes.py`. All times in seconds from the start of `Rewind (4).mp3` "
         "(decoded length 232.400 s via ffmpeg/librosa; the container reports 232.44). mm:ss.mmm in tables.\n")
L.append("## Method\n")
L.append("- Vocal separation: UVR MDX-Net `Kim_Vocal_2` ONNX (numpy re-implementation, CPU, ~2 min) -> `stems/vocals.wav`, `stems/no_vocals.wav` "
         "(demucs/HF/pytorch hosts are blocked by the proxy; GitHub-hosted UVR weights work). Stems are gitignored.\n"
         "- Beats/downbeats: madmom RNNDownBeatProcessor + DBN (4/4, 110-140 BPM) on the full mix, de-quantised by local linear fit. "
         "Cross-checked with librosa (agrees within ~25 ms, constant offset) and a comb-filter tempo fit.\n"
         "- Words: Cloudflare Workers AI `@cf/openai/whisper-large-v3-turbo` on the vocal stem (word timestamps), "
         "sequence-aligned to the lyric sheet, then edges snapped to vocal-stem activity (-45 dBFS, 10 ms). "
         "Tape-stop tails, inhales and a few phrase starts were hand-verified on 10 ms energy / spectral-flatness traces.\n"
         "- Envelopes: `envelopes.json`, 30 fps (frame i = i/30 s), keys rms/low/mid/high/vocal/inst/onset, each 0..1.\n")
L.append(f"\n## Tempo\n\nMedian **{T['bpm']} BPM** (the brief's 124 is wrong - it's ~130). 4/4, {len(T['bars'])} bars, bar 1 = {T['bars'][0]['t']:.3f}s. "
         "Drift: intro ~126, verse1 ~127.5, build1 ~129, drop1/verse3 ~129.2-129.5, build2/drop2 ~129.8-130.1, breakdown ~128 (loose), "
         "final drop ~130.0, outro slows to ~126. The intro is NOT really unmetered: kalimba/ticks already pulse at ~126 BPM and madmom's grid "
         "from 0.118 s is consistent with everything after; treat bars 1-7 as low-confidence. All three drops land exactly on downbeats "
         "(bars 25, 57, 93) of one continuous grid, so bar numbering is stable through the tape stops.\n")
L.append("\n## Sections\n\n| # | section | start | end | bar | BPM | notes |\n|---|---|---|---|---|---|---|")
for i,s in enumerate(T['sections']):
    L.append(f"| {i} | **{s['name']}** | {f(s['start'])} | {f(s['end'])} | {s['bar_start'] or ''} | {s['bpm'] or ''} | {s['note']} |")
L.append("\n## Lyric lines (as sung)\n\n| # | start | end | line |\n|---|---|---|---|")
for i,l in enumerate(T['lines']):
    L.append(f"| {i} | {f(l['start'])} | {f(l['end'])} | {l['text']} |")
L.append("\n### Deviations from the lyric sheet\n")
L.append("- \"time stops\" (both loops): \"and time\" is sung over the tape-stop silence and the drop hits ON \"(s)tops\" (45.20 / 104.56). Whisper hears \"and time's\".\n"
         "- After loop 1 the drop opens with echoed \"stop, stop, stop\" (45.5-46.8), then pitched-down hoots heard as \"boys, boys...\" (56.9-60.1) and chops through 72.5.\n"
         "- \"Rewind.\" is sung TWICE after tape stop 2 (112.14, 115.72); the sheet has one.\n"
         "- Verse-3 line \"And now I'm back on the road\" actually starts 73.55 (71.2-72.5 is a chop). \"Reload\" at 82.98 follows \"mirror\" without an audible pause.\n"
         "- Whisper mishears: \"a man in shades\" (men), \"down a Lake Shore\", \"I think stand across\" (zigzag), \"couldn't play\" (place). Lyric sheet treated as ground truth.\n"
         "- \"Never\" is buried in the build-3 choir (~169.8, medium confidence); \"stop\" is exposed alone in the hard cut 170.62-171.26.\n"
         "- Final drop + outro: chopped vocal repeatedly heard as \"I dreamt\" (171.5-227.3) and a last chop \"amen\"-like at 227.3. See `vocal_chops` in timing.json.\n")
L.append("\n## Key events\n\n| t | type | note |\n|---|---|---|")
for e in T['events']:
    L.append(f"| {f(e['t'])}{(' - '+f(e['end'])) if 'end' in e else ''} | {e['type']} | {e.get('note','')} |")
L.append("""
## Top 20 sync points for the editor

| # | time | what | use |
|---|---|---|---|
| 1 | 00:06.780 | intro low impact/braam (bar 4 beat 3) | first hard cut / title hit |
| 2 | 00:13.550 | "The night before..." verse 1 begins (bar 8 = 13.452) | car on Lake Shore Drive |
| 3 | 00:28.530 | build 1 starts (bar 16); "I pulled over" 29.56 | brake lights, pull over |
| 4 | 00:37.080 | "ID" ("I reach for my ID" from 35.93) | hand to wallet |
| 5 | 00:42.890 | "shot" #1 (sh-onset); noise-burst SFX 43.24 | muzzle flash |
| 6 | 00:43.420 | tape stop #1 (dive to 43.92) | freeze / time-stop |
| 7 | 00:43.730 | sharp inhale #1 | breath, frame hold |
| 8 | 00:44.880 | "stops" -> DROP 1 at 00:45.201 (bar 25) | REWIND effect starts |
| 9 | 00:52.260 / 00:56.000 | "Rewind." x2 | rewind typography |
| 10 | 01:13.550 | "And now I'm back on the road" (loop 2) | back in the car |
| 11 | 01:22.980 | "Reload." | reload / loop counter |
| 12 | 01:29.260 | "zigzag" (build 2 bar 49 = 89.773) | field chase |
| 13 | 01:42.280 | "shot" #2; SFX 102.56; tape stop 102.84; inhale 103.11 | second death |
| 14 | 01:44.556 | DROP 2 (bar 57), "stops" lands on it | rewind 2 |
| 15 | 01:52.140 / 01:55.720 | "Rewind." x2 | |
| 16 | 02:14.090 | breakdown (kalimba) + braams 137.41 / 141.60 / 145.38 | search-tree / chess beats |
| 17 | 02:27.820 | "The night before..." reprise; total drop-out 149.12-151.20 | loop 3 decision |
| 18 | 02:44.098 | build 3 (bar 89) rising to hard cut 170.62 ("stop" alone) | keep driving |
| 19 | 02:51.542 | FINAL DROP (bar 93) after true silence 171.28-171.50 | "Never stop." payoff |
| 20 | 03:35.858 / 03:47.200 | outro starts / abrupt end hit (tail to ~231.5) | final image / cut to black |
""")
L.append("\n## Confidence / caveats\n\n- Beat grid: high in all drop/verse3/build2 sections (+-10 ms), medium in verse1/build1 and breakdown (sparse, rubato-ish percussion), low in intro bars 1-7.\n"
         "- Word timings: line starts/ends +-50 ms where checked by hand (all 'shot/time/stops', verse openers); other word-internal boundaries +-100-150 ms (whisper ends + energy snapping). Words sung under drops (\"Rewind\") are harder to verify because chops overlap in the vocal stem.\n"
         "- `kicks`: beats in drop1/verse3/build2/drop2/final_drop snapped to the 30-90 Hz onset (+-40 ms); the distorted sub sits on the offbeats, so use beats, not raw low-band energy, for kick flashes.\n"
         "- `hits`: mel spectral-flux peaks with relative strength `s` (0..1) and dominant band; threshold s>0.5 for big hits.\n"
         "- The madmom grid keeps ticking through the tail; musical grid ends at `grid_end` = 227.20.\n")
open('TIMING_NOTES.md','w').write('\n'.join(L))
